# Generated by Django 2.2.7 on 2019-11-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('contact_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('tran_log_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('job_desc', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('modified_dttm', models.DateTimeField(auto_now=True, null=True)),
                ('ref_field_1', models.CharField(max_length=50, null=True)),
                ('ref_field_2', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('contact_log_id',),
            },
        ),
        migrations.CreateModel(
            name='TranLog',
            fields=[
                ('tran_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=10)),
                ('tran_type', models.CharField(max_length=5)),
                ('tran_code', models.CharField(max_length=5)),
                ('data', models.CharField(max_length=10000, null=True)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('modified_dttm', models.DateTimeField(auto_now=True, null=True)),
                ('ref_field_1', models.CharField(max_length=50, null=True)),
                ('ref_field_2', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('tran_log_id',),
            },
        ),
    ]
