# Generated by Django 2.2.7 on 2019-11-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tranlog_client_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextUp',
            fields=[
                ('next_up_id', models.AutoField(primary_key=True, serialize=False)),
                ('next_up_type', models.CharField(max_length=25)),
                ('next_up_value', models.IntegerField()),
                ('increment', models.IntegerField()),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('modified_dttm', models.DateTimeField(auto_now=True, null=True)),
                ('ref_field_1', models.CharField(max_length=50, null=True)),
                ('ref_field_2', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('next_up_type',),
            },
        ),
        migrations.RemoveField(
            model_name='tranlog',
            name='tran_code',
        ),
        migrations.RemoveField(
            model_name='tranlog',
            name='tran_type',
        ),
        migrations.AddField(
            model_name='tranlog',
            name='tran_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
