# Generated by Django 2.2.7 on 2019-11-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191112_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlog',
            old_name='tran_log_id',
            new_name='tran_id',
        ),
    ]
