# Generated by Django 2.2.7 on 2019-11-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191112_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='did_reply',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
