# Generated by Django 2.2.7 on 2019-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactlog_did_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='is_archieved',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
