# Generated by Django 2.2.7 on 2019-11-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactlog_is_archieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlog',
            old_name='is_archieved',
            new_name='is_archived',
        ),
    ]
