# Generated by Django 2.2.7 on 2019-11-14 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191114_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='reply_by',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
