# Generated by Django 2.2.7 on 2019-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_publicip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranlog',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tranlog',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tranlog',
            name='lat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tranlog',
            name='lon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tranlog',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tranlog',
            name='threat_level',
            field=models.CharField(default='low', max_length=10),
        ),
    ]
