export const UPDATE_LOGIN_MODAL_DISPLAY = 'UPDATE_LOGIN_MODAL_DISPLAY'
export const UPDATE_CONTACT_MODAL_DISPLAY = 'UPDATE_CONTACT_MODAL_DISPLAY'
export const UPDATE_PAGE_STATE = 'UPDATE_PAGE_STATE'
export const UPDATE_TOAST_MSG= 'UPDATE_TOAST_MSG'


export const DO_LOGIN = 'DO_LOGIN'
export const DO_LOGOUT = 'DO_LOGOUT'
export const ACCOUNT_SET_NAME = 'ACCOUNT_SET_NAME'
export const ACCOUNT_SET_ANON = 'ACCOUNT_SET_ANON'
export const ACCOUNT_SET_LOGIN_ERROR = 'ACCOUNT_SET_LOGIN_ERROR'
export const ACCOUNT_SET_WAITING_FOR_AUTH = 'ACCOUNT_SET_WAITING_FOR_AUTH'
export const ACCOUNT_INITIATE_LOGOUT = 'ACCOUNT_INITIATE_LOGOUT'
export const ACCOUNT_SET_TOKEN = 'ACCOUNT_SET_TOKEN'
